# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Branch in git we are going to target.

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

# @ specifies the version number. so @2 = version 2.
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    selectOrConfig: 'config'
    nugetConfigPath: 'ToDoListWebAPI/SolutionItems/NuGet.config'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
